// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThAmCo.Catering.DataModels;

namespace ThAmCo.Catering.Migrations
{
    [DbContext(typeof(ThAmCo_CateringDBContext))]
    [Migration("20211111190210_InitailDatabaseDesign")]
    partial class InitailDatabaseDesign
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThAmCo.Catering.DataModels.FoodBooking", b =>
                {
                    b.Property<int>("FoodBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientReferenceId")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.HasKey("FoodBookingId");

                    b.HasIndex("MenuId");

                    b.ToTable("FoodBookings");

                    b.HasData(
                        new
                        {
                            FoodBookingId = 1,
                            ClientReferenceId = 123,
                            MenuId = 2,
                            NumberOfGuests = 4
                        },
                        new
                        {
                            FoodBookingId = 2,
                            ClientReferenceId = 145,
                            MenuId = 1,
                            NumberOfGuests = 3
                        },
                        new
                        {
                            FoodBookingId = 3,
                            ClientReferenceId = 111,
                            MenuId = 2,
                            NumberOfGuests = 1
                        },
                        new
                        {
                            FoodBookingId = 4,
                            ClientReferenceId = 137,
                            MenuId = 3,
                            NumberOfGuests = 5
                        },
                        new
                        {
                            FoodBookingId = 5,
                            ClientReferenceId = 120,
                            MenuId = 4,
                            NumberOfGuests = 8
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.FoodItem", b =>
                {
                    b.Property<int>("FoodItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FoodItemId1")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("FoodItemId");

                    b.HasIndex("FoodItemId1");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            FoodItemId = 1,
                            Description = "Tacos",
                            UnitPrice = 8.13f
                        },
                        new
                        {
                            FoodItemId = 2,
                            Description = "TunaSandwich",
                            UnitPrice = 2.95f
                        },
                        new
                        {
                            FoodItemId = 3,
                            Description = "Risotto",
                            UnitPrice = 10.21f
                        },
                        new
                        {
                            FoodItemId = 4,
                            Description = "CheeseBurger ",
                            UnitPrice = 5.64f
                        },
                        new
                        {
                            FoodItemId = 5,
                            Description = "ChickenWings",
                            UnitPrice = 3.37f
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MenuName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuName = "BurgersKings"
                        },
                        new
                        {
                            MenuId = 2,
                            MenuName = "ComfortFood"
                        },
                        new
                        {
                            MenuId = 3,
                            MenuName = "ChickenPotPie"
                        },
                        new
                        {
                            MenuId = 4,
                            MenuName = "TacoBell"
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.MenuFoodItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<int?>("MenuId1")
                        .HasColumnType("int");

                    b.HasKey("MenuId", "FoodItemId");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MenuId1");

                    b.ToTable("MenuFoodItems");

                    b.HasData(
                        new
                        {
                            MenuId = 3,
                            FoodItemId = 3
                        },
                        new
                        {
                            MenuId = 1,
                            FoodItemId = 4
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 5
                        },
                        new
                        {
                            MenuId = 2,
                            FoodItemId = 2
                        },
                        new
                        {
                            MenuId = 4,
                            FoodItemId = 1
                        });
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.FoodBooking", b =>
                {
                    b.HasOne("ThAmCo.Catering.DataModels.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.FoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.DataModels.FoodItem", null)
                        .WithMany("foodItms")
                        .HasForeignKey("FoodItemId1");
                });

            modelBuilder.Entity("ThAmCo.Catering.DataModels.MenuFoodItem", b =>
                {
                    b.HasOne("ThAmCo.Catering.DataModels.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.DataModels.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThAmCo.Catering.DataModels.Menu", null)
                        .WithMany("MenuFoods")
                        .HasForeignKey("MenuId1");
                });
#pragma warning restore 612, 618
        }
    }
}
